services:
  api:
    build:
      context: .
      dockerfile: JuntoChallenge.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
    networks:
      - devnet

networks:
  devnet:
    external: true
    